name: Deploy Preview

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache public
        uses: actions/cache@v1
        with:
          path: public
          key: ${{ runner.os }}-public-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-public-

      - name: Cache gatsby cache
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install
        run: npm ci

      - name: Build
        run: PATH_PREFIX=preview/${{ github.event.number }} npm run build -- --prefix-paths

      - name: Deploy
        if: success()
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: significa.dev
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_PREVIEW_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_PREVIEW_SECRET }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: 'public'
          DEST_DIR: preview/${{ github.event.number }}

      - name: Deploy message
        if: success()
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: Deploy preview ready! https://significa.dev/preview/${{ github.event.number }}
